modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = ""

[[mods]]
modId = "endfieldind"
version = "${version}"
displayName = "EndFieldIndustries"
authors = "APcp"
description = '''
'''
#logoFile = ""

[[dependencies.endfieldind]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endfieldind]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
